apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - image: michaelsamirjacob/udagram-api-user:v1
        name: udagram-api-user 
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.2"
          limits:
            memory: "2048Mi"
            cpu: "2" 
        envFrom:
        - configMapRef:
            name: env-configmap   
        - secretRef:
            name: env-secret
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always          
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret